/*-
 * ===========================================================================
 * guidelines-archunit
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Copyright (C) 2019 - 2026 Kapralov Sergey
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * ============================================================================
 */
package com.pragmaticobjects.oo.guidelines.archunit.archunit.conditions;

import com.pragmaticobjects.oo.guidelines.archunit.archunit.exclusions.ConstructorCallsExclusion;
import com.pragmaticobjects.oo.guidelines.archunit.archunit.exclusions.FieldAccessExclusion;
import com.tngtech.archunit.core.domain.JavaModifier;
import io.vavr.collection.List;

import static com.tngtech.archunit.core.domain.JavaClass.Predicates.type;
import static com.tngtech.archunit.core.domain.JavaCodeUnit.Predicates.constructor;
import static com.tngtech.archunit.core.domain.properties.HasModifiers.Predicates.modifier;

/**
 * ArchUnit condition that recognizes primary constructors.
 *
 * <p>A primary constructor is expected to be the only constructor that performs
 * direct object state initialization. During the deep constructor analysis this
 * condition treats access to {@code final} fields as legitimate, because setting
 * immutable attributes is the primary constructor's responsibility.</p>
 *
 * <p>All other field accesses and method or constructor calls are reported as
 * violations unless they are covered by explicitly configured exclusions. The
 * default call exclusion ignores the implicit call to {@link Object}'s
 * constructor, because it is generated by the Java compiler and does not
 * represent domain logic in the analyzed constructor.</p>
 *
 * <p>Use the constructor with additional exclusions when a project-specific
 * safe field access or call should be accepted without weakening the default
 * primary-constructor semantics.</p>
 */
public class BePrimaryConstructor extends DeepConstructorAnalysisCondition {
    /**
     * Ctor. Uses default exclusions (final field assignments and {@code Object} super call).
     */
    public BePrimaryConstructor() {
        this(
            List.empty(),
            List.empty()
        );
    }

    /**
     * Ctor.
     *
     * @param additionalFieldAccessExclusions  extra field-access patterns allowed in a primary constructor
     * @param additionalCtorCallsExclusion     extra constructor-call patterns allowed in a primary constructor
     */
    public BePrimaryConstructor(
        List<FieldAccessExclusion> additionalFieldAccessExclusions,
        List<ConstructorCallsExclusion> additionalCtorCallsExclusion
    ) {
        super(
            "primary",
            List.of(
                new FieldAccessExclusion(
                    // primary constructors set final attributes
                    modifier(JavaModifier.FINAL).forSubtype()
                )
            ).appendAll(additionalFieldAccessExclusions),
            List.of(
                new ConstructorCallsExclusion(
                    // Calling constructor of java.lang.Object is generated by Java compiler,
                    // so we ignore it
                    type(Object.class),
                    constructor()
                )
            ).appendAll(additionalCtorCallsExclusion)
        );
    }
}
