/*-
 * ===========================================================================
 * guidelines-archunit
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Copyright (C) 2019 - 2026 Kapralov Sergey
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 * ============================================================================
 */
package com.pragmaticobjects.oo.guidelines.archunit.archunit;

import com.pragmaticobjects.oo.guidelines.archunit.ArchitecturalExclusion;
import com.tngtech.archunit.base.DescribedPredicate;
import com.tngtech.archunit.core.domain.JavaClass;
import com.tngtech.archunit.core.domain.JavaMethod;
import com.tngtech.archunit.core.domain.JavaModifier;
import com.tngtech.archunit.core.domain.properties.CanBeAnnotated;
import com.tngtech.archunit.core.domain.properties.HasType;

import static com.tngtech.archunit.base.DescribedPredicate.*;
import static com.tngtech.archunit.core.domain.JavaClass.Predicates.*;
import static com.tngtech.archunit.core.domain.properties.CanBeAnnotated.Predicates.annotatedWith;
import static com.tngtech.archunit.core.domain.properties.HasModifiers.Predicates.modifier;

/**
 * Common ArchUnit predicates used by guideline checks.
 */
public class Items {
    private Items() {
    }

    public static DescribedPredicate<JavaMethod> TEST_METHOD = annotatedWith(
        HasType.Predicates.rawType(
            resideInAPackage(
                "org.junit.jupiter.."
            )
        )
    ).forSubtype();

    public static DescribedPredicate<CanBeAnnotated> ARCHITECTURAL_EXCLUSION = annotatedWith(
        ArchitecturalExclusion.class
    );

    public static DescribedPredicate<JavaClass> EQUIVALENCE_COMPLIANT_CLASS = implement(
        "com.pragmaticobjects.oo.equivalence.base.EquivalenceCompliant"
    );

    public static DescribedPredicate<JavaClass> EQUIVALENCE_COMPLIANT_SELFTESTING_SCOPE = and(
        // We take into scope all classes from the package
        resideInAPackage(
            "com.pragmaticobjects.oo.equivalence.."
        ),
        not(
            // excluding those, which implement something from outside
            implement(
                not(
                    resideInAPackage(
                        "com.pragmaticobjects.oo.equivalence.."
                    )
                )
            )
        )
    );

    /**
     * Test classes
     */
    public static DescribedPredicate<JavaClass> TESTS = or(
        containAnyMethodsThat(TEST_METHOD),
        assignableTo(
            containAnyMethodsThat(TEST_METHOD)
        )
    );

    /**
     * Methods, directly declared in code (not implicitly generated by compiler or other tools)
     */
    public static DescribedPredicate<JavaMethod> DECLARED_METHODS = not(
        or(
            modifier(JavaModifier.SYNTHETIC),
            modifier(JavaModifier.BRIDGE)
        )
    );

    public static DescribedPredicate<JavaClass> BUSINESS_CODE = or(
        EQUIVALENCE_COMPLIANT_CLASS,
        EQUIVALENCE_COMPLIANT_SELFTESTING_SCOPE
    ).as("business logic");

    /**
     * Abstract interfaces
     */
    public static DescribedPredicate<JavaClass> ABSTRACTIONS = and(
        BUSINESS_CODE,
        INTERFACES
    );


    public static DescribedPredicate<JavaClass> SEMI_ABSTRATCIONS = and(
        BUSINESS_CODE,
        modifier(JavaModifier.ABSTRACT)
    );

    /**
     * Concrete interface implementations
     */
    public static DescribedPredicate<JavaClass> CONCRETICS = and(
        BUSINESS_CODE,
        not(INTERFACES),
        not(SEMI_ABSTRATCIONS)
    );

    public static DescribedPredicate<JavaClass> INFERENCES = and(
        BUSINESS_CODE,
        or(
            implement("com.pragmaticobjects.oo.inference.api.Inference"),
            implement(
                simpleNameContaining("Inference")
            )
        )
    );
}
