name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.3.1
        with:
          java-version: '17'
          distribution: temurin
          gpg-private-key: ${{secrets.GPG_SIGN}}
          gpg-passphrase: GPG_PASSPHRASE
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
      - name: Build tools
        run: ./mvnw clean install -B -Pbuild-tools -Djgitver.skip=true
      - name: Release
        run: ./mvnw clean deploy -B -Pmodules,ossrh,extras -Djgitver.use-version=${GITHUB_REF##*/}
        env:
          GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
          OSSRH_USERNAME: ${{secrets.OSSRH_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}